replicaCount: 1

image:
  repository: "534856791031.dkr.ecr.us-east-1.amazonaws.com/devops-shop"
  tag: ""
  digest: "sha256:e478f59f811a09fa9fcf566ca19b2dc1c96c090392ce35278709a4a255f5303a"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi

  limits:
    cpu: 500m
    memory: 512Mi

probes:
  path: /health

ingress:
  enabled: false
  host: devops-shop-staging.local

monitoring:
  enabled: false

serviceMonitor:
  enabled: true
  interval: 15s
  # Must match the release name of your installed kube-prometheus-stack release
  release: prometheus

alerting:
  enabled: true

  rules:
    highErrorRate:
      enabled: true
      threshold: 5
      for: 5m

    highLatency:
      enabled: true
      threshold: 0.5
      for: 5m

    appDown:
      enabled: true
      for: 2m
      
alertmanager:
  alertmanagerSpec:
    secrets:
      - alertmanager-slack